name: gh-pages-syncer

on:
  push:
    branches:
      - main

jobs:
  sync-gh-pages:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout gh-pages branch
        uses: actions/checkout@v4
        with:
          ref: 'gh-pages'

      - name: Pull and Push
        run: |
          git config --global user.name 'gh-pages-updater'
          git config --global user.email 'gh-pages-updater@users.noreply.github.com'
          git pull origin main
          git push origin gh-pages
